
environment:

  matrix:

    - PYTHON: "C:\\Python37_64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Don't install from requirements-pip.txt, python-coveralls has broken dependencies on windows it seems.
  - conda install --yes setuptools nose numpy scipy pip coverage scipy pandas six scikit-learn=0.22.1 ipython
  - pip install -I pyprind==2.9.8
  - pip install -r requirements.txt
  - python setup.py install
  - conda install -c intel numpy mkl-service --yes

build: false

test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - nosetests
  #- behave --tags ~@skip # Everything without the tag @skip

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  #- coverage report
  # coveralls
