name: py_wholebodymovement_dev
channels:
  - conda-forge
  - adelaneh
  - defaults
dependencies:
    - setuptools
    - pandas
    - nose
    - numpy
    - scipy
    - scikit-learn=0.22.1
    - pywavelets
