name: py_wholebodymovement_dev
channels:
  - conda-forge
  - adelaneh
  - defaults
dependencies:
    - python=3.7.0
    - setuptools
    - pandas
    - nose
    - numpy
    - scipy
    - scikit-learn=0.22.1
    - matplotlib
    - notebook=5.7.8
    - jupyter_contrib_nbextensions
    - pywavelets
